Ensure the correct pipeline file is present
bugsnag/bugsnag-expo pull request #5
Opened 2022-03-08 17:09 UTC by Cawllec

## Goal

Moves the correct pipeline file over from bugsnag-js

2022-03-08 17:16 UTC, imjoehaines requested changes

2022-03-08 17:16 UTC, imjoehaines commented on .buildkite/pipeline.yml
> -      BUILD_RN_WITH_LATEST_NATIVES: ${BUILD_RN_WITH_LATEST_NATIVES}
The "trigger Expo pipeline" step has `depends_on: 'publish-js'`, so I assume this is still needed ?

2022-03-08 17:16 UTC, imjoehaines commented on .buildkite/pipeline.yml
> -    command: scripts/license_finder.sh
AFAIK we still need this in every repo

2022-03-08 17:16 UTC, imjoehaines commented on .buildkite/pipeline.yml
> -    command: 'npm run test:unit'
This is all still needed as well

2022-03-09 08:28 UTC, Cawllec commented
This change is unnecessary, and can be closed

2022-03-09 08:28 UTC, closed without merging